# Generated by Django 6.0.1 on 2026-02-01 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship_no',
            field=models.CharField(help_text='Government Citizenship ID', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Invalid Citizenship Number')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(help_text='Ethereum Wallet Address', max_length=42, unique=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{40}$', 'Invalid Ethereum Address')]),
        ),
    ]
