# Generated by Django 6.0.1 on 2026-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_userprofile_citizenship_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='land_image',
            field=models.ImageField(blank=True, null=True, upload_to='land_pictures/'),
        ),
    ]
