# Generated by Django 6.0.1 on 2026-04-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_registrationapplication_land_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
