# Generated by Django 6.0.1 on 2026-04-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_registrationapplication_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship_no',
            field=models.CharField(help_text='Government Citizenship ID', max_length=20, unique=True),
        ),
    ]
