# Generated by Django 6.0.1 on 2026-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_userprofile_citizenship_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if applicable', null=True),
        ),
    ]
