# Generated by Django 6.0.1 on 2026-04-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_registrationapplication_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/citizenship_back/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/citizenship_front/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship_issue_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/profiles/'),
        ),
    ]
