# Generated by Django 6.0.1 on 2026-04-29 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_authorizedofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.registrationapplication'),
        ),
        migrations.AlterField(
            model_name='authorizedofficer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set to True once the officer   completes onboarding'),
        ),
    ]
