# Generated by Django 6.0.1 on 2026-04-29 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_adminactionlog_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('citizenship_no', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('citizenship_issue_district', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='kyc_updates/profiles/')),
                ('citizenship_front', models.ImageField(blank=True, null=True, upload_to='kyc_updates/citizenship_front/')),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to='kyc_updates/citizenship_back/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_updates', to='registry.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
