# Generated by Django 6.0.1 on 2026-04-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_kycupdaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.IntegerField(help_text='Blockchain Parcel ID', unique=True)),
                ('location', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('land_image', models.ImageField(blank=True, null=True, upload_to='land_pictures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='registry.userprofile')),
                ('original_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_record', to='registry.registrationapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(help_text='Ethereum Transaction Hash', max_length=66)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='registry.userprofile')),
                ('property_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='registry.propertyrecord')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='registry.userprofile')),
            ],
        ),
    ]
