# Generated by Django 6.0.1 on 2026-05-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_propertyrecord_transferlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationapplication',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in square meters', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='document_path',
            field=models.ImageField(help_text='Scanned copy of the original handwritten land deed (Lalpurja)', upload_to='deeds/'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='land_image',
            field=models.ImageField(blank=True, help_text='Photograph of the land parcel', null=True, upload_to='land_pictures/'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location/address of the land', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='parcel_id',
            field=models.IntegerField(blank=True, help_text='Linked Blockchain Parcel ID (assigned upon approval)', null=True),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='user',
            field=models.ForeignKey(help_text='The citizen who originally applied for registration', on_delete=django.db.models.deletion.CASCADE, to='registry.userprofile'),
        ),
    ]
