# Generated by Django 6.0.1 on 2026-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_registrationapplication_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlog',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Simulated sale price in NPR', max_digits=15, null=True),
        ),
    ]
