# Generated by Django 6.0.1 on 2026-05-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_transferlog_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Ethereum Transaction Hash (Minting Event)', max_length=66, null=True),
        ),
    ]
