# Generated by Django 6.0.1 on 2026-05-05 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_registrationapplication_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrecord',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Area must be greater than zero.')]),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in square meters', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Area must be greater than zero.')]),
        ),
    ]
