# Generated by Django 6.0.1 on 2026-05-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedofficer',
            name='department',
            field=models.CharField(choices=[('Land Revenue', 'Land Revenue'), ('Survey & Mapping', 'Survey & Mapping'), ('Digital Registry', 'Digital Registry')], default='Land Revenue', max_length=50),
        ),
        migrations.AddField(
            model_name='authorizedofficer',
            name='designation',
            field=models.CharField(choices=[('District Registrar', 'District Registrar'), ('Land Revenue Officer', 'Land Revenue Officer'), ('Assistant Officer', 'Assistant Officer'), ('Verification Specialist', 'Verification Specialist')], default='Land Revenue Officer', max_length=50),
        ),
        migrations.AddField(
            model_name='authorizedofficer',
            name='office_branch',
            field=models.CharField(default='Kathmandu LRO', help_text='Physical branch location (e.g. Dilli Bazar)', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(help_text='e.g., Approve Land Application, Reject KYC', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='remarks',
            field=models.TextField(blank=True, help_text="Officer's justification for the action", null=True),
        ),
        migrations.AlterField(
            model_name='authorizedofficer',
            name='employee_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
